spring:
  application:
    name: authentication-service


  config:
    import:
      "optional:configserver:http//localhost:8088"

  jpa:
    show_sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        hbm2ddl:
          auto: "update"

  datasource:
    url: "jdbc:mysql://localhost:3306/auth_db"
    username: "root"
    password: "123456789"

