
server:
  port:
    6000


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/auth/**
          filters:
            - AuthFilter
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - AuthFilter
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/image/**
          filters:
            - AuthFilter
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/recommendation/**
          filters:
            - AuthFilter
        - id: websocket
          uri: lb://websocket
          predicates:
            - Path=/chat/**
          filters:
            - AuthFilter
eureka:
  instance:
    prefer-ip-address: true
